### ISSUE TITLE
I want to use my styler license key on a new device

### ISSUE THREAD

**Issue by Piotrgitter** [oodesign/sketch-styler#11]
Hi there, styler is awesome! Great work!
Some days ago I purchased a styler license key. Now I changed my device and can't get it running "All seats are busy!". I can't find a way to unregister styler on the other device.
Do I really have to buy a new key when changing my device?
Cheers

**Comment by oodesign** [comment]
Hi @Piotrgitter ,

We're trying to keep this space just for technical issues related with the plugin.
May I ask you to [send me an e-mail](mailto:oscar@oodesign.me) (with some details like the e-mail account you used for the purchase) so that we can continue the conversation there?

Thank you! 😉

Òscar from oodesign
