### ISSUE TITLE
Just payed for my license but Styler doesn't work

### ISSUE THREAD

**Issue by pzecca73** [oodesign/sketch-styler#27]
![Bitmap](https://user-images.githubusercontent.com/106964562/172145341-a60beb2c-d6b2-4df9-af34-a066a4ad8d0f.jpg)

It stops and doesn't finish the search for matching styles

**Comment by oodesign** [comment]
Hi @pzecca73 ,

I'm sorry Styler is not working well for you :( 

To investigate a bit further your issue, may you please send us the Sketch Styler logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Sketch Styler logs are disabled by default. You may enable them by going to Plugins > Sketch Styler > Settings , and switching on the logging ability.
4. Run the Sketch Styler command you were having issues with.
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit and reopen the app).
6. Logs will be stored by this point. May you please [send us](mailto:support@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by vburzynski** [comment]
I was using the trial, but Sketch Styler is also not working for me. The `sketch-dev-tools` displays an error when I open the plugin interface:
```
TypeError: NSApp.delegate().librariesController().libraries is not a function. (In 'NSApp.delegate().librariesController().libraries()', 'NSApp.delegate().librariesController().libraries' is undefined)
```
[Plugin Log.log](https://github.com/oodesign/sketch-styler/files/10076861/Plugin.Log.log)

**Comment by oodesign** [comment]
Hi @vburzynski ,

We can reproduce the issue and we're already working on it.
I'll be happy to let you know when we're able to release a fix.

Thanks for reaching out! 🥰

**Comment by oodesign** [comment]
Hi @vburzynski and @pzecca73 ,

I'm afraid this is an issue we won't be able to solve 😔.

Due to Sketch recent changes (and low support on plugin infrastructure) fixing this issue would require us a major code approach effort and, after considering it with the team, we have to admit that we feel it's not worth it.

Therefore, we took the (sad) decision to discontinue Sketch Styler.

If you did purchase a Styler license from June 2022 (when this issue was first reported) until November 2022, please [send us an email](mailto:support@oodesign.me) with your purchase details and your license key, and we'd be happy to refund you the total amount of your purchase.

We sincerely apologize for all the inconvenience this may have caused you.

All the best

**Comment by pzecca73** [comment]
[Edited by moderator] - We're removing this comment as it discloses license details. If you feel this was inappropriate please send us an email at support@oodesign.me so that we can continue the conversation there.

Thanks!

**Comment by oodesign** [comment]
Oh, my apologies, of course we're counting you on the refund.

We initially thought that the last 2 months would be backwards enough, but considering it'd make way more sense to offer them since this issue was first raised (June 2022). 

I'm updating the previous comment. I'll also remove your last comment as it discloses license details, but please feel free to reopen the issue or continue the thread if you wish to. 

Thanks!

**Comment by pzecca73** [comment]
I don’t use sketch anymore so I’d like the refund, how do I have to process to have it?

Il giorno 24 nov 2022, alle ore 10:58, Oscar Oto ***@***.******@***.***>> ha scritto:



Oh, my apologies, of course we're counting you on the refund.

We initially thought that the last 2 months would be backwards enough, but considering it'd make way more sense to offer them since this issue was first raised (June 2022).

I'm updating the previous comment. I'll also remove your last comment as it discloses license details, but please feel free to reopen the issue or continue the thread if you wish to.

Thanks!

**Comment by oodesign** [comment]
Please [send us an email](mailto:support@oodesign.me) with:
- The email you used to acquire your license on Gumroad
- Your Sketch Styler license key

Thanks!

**Comment by pzecca73** [comment]
What is Gumroad?
Where do I recover the license key from? I do not have access to Sketch anymore because the license wasn’t personal but business of an agency I don’t work for anymore



Il giorno 24 nov 2022, alle ore 11:21, Oscar Oto ***@***.******@***.***>> ha scritto:



Please send us an ***@***.***> with:

  *   The email you used to acquire your license on Gumroad
  *   Your Sketch Styler license key

Thanks!

**Comment by pzecca73** [comment]
Maybe both the email and the license key are the ones shown here?

[cid:8727EE81-0EE6-4B1D-86D2-3F8B86DEFADA]

Il giorno 24 nov 2022, alle ore 11:21, Oscar Oto ***@***.******@***.***>> ha scritto:



Please send us an ***@***.***> with:

  *   The email you used to acquire your license on Gumroad
  *   Your Sketch Styler license key

Thanks!
